name: S3 Deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: frontend

jobs:
  check-aws-secret:
    runs-on: ubuntu-latest
    outputs:
      key_exists: ${{ steps.check-secret.outputs.key_exists }}
    steps:
    - uses: actions/checkout@v1
    - id: check-secret
      name: Check if AWS secret exists
      run: |-
        if [ ! -z ${{ secrets.AWS_SECRET_ACCESS_KEY }} ] && \
           [ ! -z ${{ secrets.AWS_ACCESS_KEY_ID }} ] && \
           [ ! -z ${{ secrets.S3_BUCKET }} ]; then
          echo "::set-output name=key_exists::true"
        fi

  run:
    runs-on: ubuntu-latest
    needs: [check-aws-secret]
    if: ${{ needs.check-aws-secret.outputs.key_exists == 'true' }}
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Build static site
      working-directory: frontend
      run: npm ci && npm run build
    - name: Deploy static site to S3 bucket
      working-directory: frontend
      run: aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET }} --delete
  
      
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build static site
#        working-directory: frontend
#        run: npm ci && npm run build
#      - name: Deploy
#        uses: reggionick/s3-deploy@v1
#        with:
#          folder: frontend/build
#          bucket: ${{ secrets.S3_BUCKET }}
#          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
